<?php

namespace AppBundle\Repository;

/**
 * BankPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
