<?php

namespace AppBundle\Repository;

/**
 * ChargePayementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargePayementRepository extends \Doctrine\ORM\EntityRepository
{
}
