<?php

namespace AppBundle\Repository;

/**
 * MessageFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
