<?php

namespace AppBundle\Repository;

/**
 * partOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class partOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
