<?php

namespace AppBundle\Repository;

/**
 * ProjectFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
