<?php

namespace AppBundle\Repository;

/**
 * SurveyVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
