<?php

namespace AppBundle\Repository;

/**
 * SurveyOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
